import type { Metadata } from 'next';
import { Providers } from '@/ui/provider';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='es'>
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
